# Generated by Django 5.1.1 on 2024-10-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usertypes_is_barista_usertypes_is_personal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeeuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='coffeeuser',
            name='is_barista',
            field=models.BooleanField(default=False, verbose_name='Бариста'),
        ),
        migrations.DeleteModel(
            name='UserTypes',
        ),
    ]
