version: "4.2"
services:
  django:
    container_name: django
    build: .
    tty: true
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/practice/
    environment:
      - DB_NAME=practicedjango
      - DB_USER=root
      - DB_PASSWD=root
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=root
      - EMAIL_HOST_USER=mymail@gmail.com
      - EMAIL_HOST_PASSWORD=mykey
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres
    image: postgres:17.0-alpine3.20
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5342
    environment:
      - POSTGRES_DB=practicedjango
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata

  redis:
    container_name: redis
    image: redis:8.0-M02-alpine
    restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=root
      - REDIS_USER=root
      - REDIS_USER_PASSWORD=root
    
  celery:
    container_name: celery
    restart: always
    build: .
    command: celery -A aogiri worker -l INFO -E
    volumes:
      - .:/practice/
    environment:
      - DB_NAME=practicedjango
      - DB_USER=root
      - DB_PASSWD=root
      - DB_HOST=postgres
    depends_on:
      - postgres
      - redis
      - django

volumes:
  pgdata:
