"""
Django settings for aogiri project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from typing import Any

from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-9@f+*-^6$y5mj@e^%&70_6uhf_vbs(2jojh0tat-eor!$=#5-b"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_email_verification",
    
    "users",
    "products",
    "orders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "aogiri.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            Path.joinpath(BASE_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "orders.context_processors.order_manager"
            ],
        },
    },
]

WSGI_APPLICATION = "aogiri.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

load_dotenv()

db_name = os.getenv("DB_NAME")
db_user = os.getenv("DB_USER")
db_pass = os.getenv("DB_PASSWD")
db_host = os.getenv("DB_HOST")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": db_name,
        "HOST": db_host,
        "USER": db_user,
        "PASSWORD": db_pass,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / STATIC_URL]
MEDIA_URL = "media/"
MEDIAFILES_DIRS = [BASE_DIR / MEDIA_URL]
MEDIA_ROOT = BASE_DIR / MEDIA_URL

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "users.CoffeeUser"
ORDER_SESSION_ID = "user_order"


def email_verification_callback(user) -> None:
    user.email_verified = True


def password_change_callback(user, password: str | Any) -> None:
    user.set_password(password)


TOKEN_LIFE = 60 * 2

EMAIL_PAGE_DOMAIN = "http://localhost:8000/"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

EMAIL_MAIL_SUBJECT = "Подтверждение почты от Aogiri."
EMAIL_MAIL_HTML = "user_email_confirm.html"
EMAIL_MAIL_PLAIN = "email_confirm.txt"
EMAIL_MAIL_PAGE_TEMPLATE = "user_email_success.html"

EMAIL_PASSWORD_SUBJECT = "Восстановление пароля от Aogiri."
EMAIL_PASSWORD_HTML = "user_password_confirm.html"
EMAIL_PASSWORD_PLAIN = "password_confirm.txt"
EMAIL_PASSWORD_PAGE_TEMPLATE = "user_password_success.html"
EMAIL_PASSWORD_CHANGE_PAGE_TEMPLATE = "user_password_change.html"

EMAIL_FROM_ADDRESS = EMAIL_HOST_USER
EMAIL_PASSWORD_TOKEN_LIFE = TOKEN_LIFE
EMAIL_MAIL_TOKEN_LIFE = TOKEN_LIFE
 
EMAIL_MAIL_CALLBACK = email_verification_callback
EMAIL_PASSWORD_CALLBACK  = password_change_callback

CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TIME_LIMIT = TOKEN_LIFE
CELERY_BROKER_URL = "redis://redis:6379/0"
CELERY_RESULT_BACKEND = "redis://redis:6379/0"
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TASK_SERIALIZER = "json"
