# Generated by Django 5.1.1 on 2024-10-08 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Общая цена')),
                ('bonuses', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Общий бонус')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Заказ оплачен')),
                ('is_ready', models.BooleanField(default=False, verbose_name='Заказ готов')),
                ('coffe_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.coffee', verbose_name='id кофе')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.food', verbose_name='id еды')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id клиента')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mixins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk', models.BooleanField(default=False, verbose_name='Молоко')),
                ('cinnamon', models.BooleanField(default=False, verbose_name='Корица')),
                ('syrup', models.BooleanField(default=False, verbose_name='Сироп')),
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='id заказа')),
            ],
            options={
                'verbose_name': 'Добавка',
                'verbose_name_plural': 'Добавки',
                'ordering': ['id'],
            },
        ),
    ]
