# Generated by Django 5.1.1 on 2024-10-08 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mixins',
            new_name='Mixin',
        ),
    ]
