# Generated by Django 5.1.1 on 2024-10-10 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_mixins_mixin'),
        ('products', '0004_alter_coffee_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='food_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.food', verbose_name='id еды'),
        ),
    ]
