# Generated by Django 5.1.1 on 2024-10-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_food_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bonuses',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='is_bonus_used',
            field=models.BooleanField(default=False, verbose_name='Использовать бонс'),
        ),
    ]
