# Generated by Django 5.1.1 on 2024-10-12 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_bonuses_remove_order_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mixin',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='coffe_id',
            new_name='coffee',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='food_id',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
