# Generated by Django 5.1.1 on 2024-10-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='Название')),
                ('cost', models.PositiveIntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Кофе',
                'verbose_name_plural': 'Кофе',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='Название')),
                ('cost', models.PositiveIntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Еда',
                'verbose_name_plural': 'Еда',
                'ordering': ['name'],
            },
        ),
    ]
