# Generated by Django 5.1.1 on 2024-11-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_coffee_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='cinnamon',
            field=models.BooleanField(default=False, verbose_name='Корица'),
        ),
        migrations.AddField(
            model_name='coffee',
            name='milk',
            field=models.BooleanField(default=False, verbose_name='Молоко'),
        ),
        migrations.AddField(
            model_name='coffee',
            name='syrup',
            field=models.BooleanField(default=False, verbose_name='Сироп'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='volume',
            field=models.PositiveIntegerField(default=0, verbose_name='Объем (мл)'),
        ),
    ]
