# Generated by Django 5.1.1 on 2024-11-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_coffee_cinnamon_coffee_milk_coffee_syrup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Обложка'),
        ),
    ]
