# Generated by Django 5.1.1 on 2024-11-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_coffee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(default=None, upload_to='images/', verbose_name='Обложка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coffee',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Обложка'),
        ),
    ]
